version: "3.8"

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg123
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    network_mode: host
    healthcheck:
      test: pg_isready -d postgres://postgres:pg123@localhost:5432/mydb
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 5050
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5050:5050
    network_mode: host
